name: DWH Deployment
on: workflow_dispatch 
jobs:
    release:      
      runs-on: windows-latest
      steps:
        - name: Checkout code 
          uses: actions/checkout@v3
        - name: Display checkout files and folders
          run: Get-ChildItem ${{github.workspace}} -Recurse
        - name: Azure Login
          uses: Azure/login@v1
          with:
           creds: '{"clientId":"${{ secrets.ACTION_SPN_CLIENTID }}","clientSecret":"${{ secrets.ACTION_SPN_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        - name: Build and Deploy SQL Database
          uses: Azure/sql-action@v2
          with:
            connection-string: ${{secrets.CONTROLDB_CONNECTIONSTRING}}
            path: ${{github.workspace}}\synapse-dataplatform\dedicated-sqlpools\dw01\Database.sqlproj
            action: 'Publish'
            arguments: '/p:DropPermissionsNotInSource=false /p:DropRoleMembersNotInSource=false /p:DropObjectsNotInSource=true /p:IgnoreColumnOrder=true /p:IgnorePermissions=true /v:DatalakeEndpoint="badatalake01kn3acb6lw3vr.dfs.core.windows.net/"'
        - name: Azure Logout
          run: |
            az logout
