name: Synapse workspace deployment
on: workflow_dispatch 
jobs:
    release:      
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: 'workspace_publish'
            path: 'arm'
        - run: Get-ChildItem ${{github.workspace}} -Recurse
        - uses: Azure/Synapse-workspace-deployment@V1.7.0
          with:
            TargetWorkspaceName: 'ba-synapse01-kn3acb6lw3vr4'
            TemplateFile: ${{github.workspace}}\arm\ba-synapseanalytics01\TemplateForWorkspace.json
            ParametersFile: ${{github.workspace}}\arm\ba-synapseanalytics01\TemplateParametersForWorkspace.json
            OverrideArmParameters:  ${{github.workspace}}\arm\parameters\prod\parameters.yaml
            environment: 'Azure Public'
            resourceGroup: 'rg-synapse-dataplatform'
            clientId: ${{secrets.ACTION_SPN_CLIENTID}}
            clientSecret: ${{secrets.ACTION_SPN_SECRET}}
            subscriptionId: ${{secrets.SUBSCRIPTION_ID}}
            tenantId: ${{secrets.TENANT_ID}}
            DeleteArtifactsNotInTemplate: 'true'
            managedIdentity: 'False'
            operation: 'deploy'
